### ISSUE TITLE
Error: java.lang.UnsupportedOperationException: null

### ISSUE THREAD

**Issue by AmiTimA** [wkspower/wks-platform-docker#2]
Getting following error while creating "Process Definition" or "Case Definition".

java.lang.UnsupportedOperationException: null

**Steps:**
1. Setup docker using following command:
`docker-compose -f docker-compose.yaml -f docker-compose.camunda7.yaml -f docker-compose.demo-data-loader.camunda7.yaml -f docker-compose.portal.yaml up -d --build`

2. Browse `http://localhost:3001/` for Case Management Portal
3. Try to create a new "Case Definition" or "Process Definition" OR edit existing one.
4. "Case Management Portal" doesn't show any issue but docker logs show following error.

**Error Logs:**
`2024-09-24 16:20:31 case-engine-rest-api-1  | 2024-09-24T10:50:31.269Z ERROR 1 --- [nio-8081-exec-3] c.w.c.r.e.GlobalExceptionHandler         : Internal Error
2024-09-24 16:20:31 case-engine-rest-api-1  | 
2024-09-24 16:20:31 case-engine-rest-api-1  | java.lang.UnsupportedOperationException: null
2024-09-24 16:20:31 case-engine-rest-api-1  | at com.wks.bpm.engine.camunda.client.C7EngineClient.deploy(C7EngineClient.java:95) ~[c7-client-1.0-SNAPSHOT.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at com.wks.bpm.engine.client.facade.DefaultBpmEngineClientFacade.deploy(DefaultBpmEngineClientFacade.java:55) ~[bpm-engine-client-1.0-SNAPSHOT.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at com.wks.caseengine.rest.server.DeploymentController.deploy(DeploymentController.java:38) ~[!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207) ~[spring-web-6.0.10.jar!/:6.0.10]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152) ~[spring-web-6.0.10.jar!/:6.0.10]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.0.10.jar!/:6.0.10]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[spring-webmvc-6.0.10.jar!/:6.0.10]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-6.0.10.jar!/:6.0.10]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.0.10.jar!/:6.0.10]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081) ~[spring-webmvc-6.0.10.jar!/:6.0.10]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974) ~[spring-webmvc-6.0.10.jar!/:6.0.10]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011) ~[spring-webmvc-6.0.10.jar!/:6.0.10]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914) ~[spring-webmvc-6.0.10.jar!/:6.0.10]
2024-09-24 16:20:31 case-engine-rest-api-1  | at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590) ~[tomcat-embed-core-10.1.10.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.0.10.jar!/:6.0.10]
2024-09-24 16:20:31 case-engine-rest-api-1  | at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[tomcat-embed-core-10.1.10.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) ~[tomcat-embed-core-10.1.10.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.10.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-10.1.10.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.10.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.10.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$FilterObservation$SimpleFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:479) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$1(ObservationFilterChainDecorator.java:340) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator.lambda$wrapSecured$0(ObservationFilterChainDecorator.java:82) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:128) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:117) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:179) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.oauth2.server.resource.web.authentication.BearerTokenAuthenticationFilter.doFilterInternal(BearerTokenAuthenticationFilter.java:145) ~[spring-security-oauth2-resource-server-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.10.jar!/:6.0.10]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91) ~[spring-web-6.0.10.jar!/:6.0.10]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.10.jar!/:6.0.10]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.10.jar!/:6.0.10]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.10.jar!/:6.0.10]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:227) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.10.jar!/:6.0.10]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.wrapFilter(ObservationFilterChainDecorator.java:240) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$AroundFilterObservation$SimpleAroundFilterObservation.lambda$wrap$0(ObservationFilterChainDecorator.java:323) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$ObservationFilter.doFilter(ObservationFilterChainDecorator.java:224) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.ObservationFilterChainDecorator$VirtualFilterChain.doFilter(ObservationFilterChainDecorator.java:137) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191) ~[spring-security-web-6.1.1.jar!/:6.1.1]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352) ~[spring-web-6.0.10.jar!/:6.0.10]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268) ~[spring-web-6.0.10.jar!/:6.0.10]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.10.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.10.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-6.0.10.jar!/:6.0.10]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.10.jar!/:6.0.10]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.10.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.10.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-6.0.10.jar!/:6.0.10]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.10.jar!/:6.0.10]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.10.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.10.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109) ~[spring-web-6.0.10.jar!/:6.0.10]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.10.jar!/:6.0.10]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.10.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.10.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.0.10.jar!/:6.0.10]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.10.jar!/:6.0.10]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.10.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.10.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166) ~[tomcat-embed-core-10.1.10.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-10.1.10.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482) ~[tomcat-embed-core-10.1.10.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[tomcat-embed-core-10.1.10.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-10.1.10.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-10.1.10.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341) ~[tomcat-embed-core-10.1.10.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391) ~[tomcat-embed-core-10.1.10.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.10.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894) ~[tomcat-embed-core-10.1.10.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741) ~[tomcat-embed-core-10.1.10.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.10.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.10.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.10.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-10.1.10.jar!/:na]
2024-09-24 16:20:31 case-engine-rest-api-1  | at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]`

**Comment by carloborsoi** [comment]
I have the same issue. Any suggestion ? @francav

**Comment by francav** [comment]
This operation is not fully functional yet. The process deployment operation is pending as per [this line](See https://github.com/wkspower/wks-platform/blob/932f6399280b4cf8bcb1968c472847719673a1ea/apps/java/libraries/c7-client/src/main/java/com/wks/bpm/engine/camunda/client/C7EngineClient.java#L94).
Camunda modeler or camunda rest api can be used while we don't have this ready.

**Comment by francav** [comment]
fixed by https://github.com/wkspower/wks-platform/commit/abc38984db7cc42a2a24e86458c9193b425a6c90
